#server config
server:
  port: 8083

#spring application config
spring:

#database config
  data:
    mongodb:
      host: localhost
      port: 27017
      database: order-service
      username: sonu_vairagi_mongo
      password: Sonu@7240
      authentication-database: admin
      # Alternatively, you can use the full URI:
      # uri: mongodb://sonu_vairagi_mongo:Sonu@7240@localhost:27017/user_service?authSource=admin